### ISSUE TITLE
Classification of surgical instruments

### ISSUE THREAD

**Issue by Meaw0415** [jihun-yoon/sisvse-dataset#2]
This is a really great study. I am very interested in this study. Can I know which surgical instruments are Robotic tools and which are Laparoscopic instruments?

**Comment by jihun-yoon** [comment]
Sorry for the late reply!

**Robotic instruments**
* Small Clip Applier
* Medium-large Clip Applier
* Harmonic Ace
* Cadiere Forceps
* Maryland Bipolar Forceps
* Stapler

**Assistive(laparoscopic) instruments**
* Suction Irrigation
* Drain Tube
* Endotip
* Gauze
* Specimen Bag
* Curved Atraumatic Grasper
* Needle

The class "TheOhter_instruments" also includes laparoscopic instruments or assistive tools such as clips.
